In [1]:
import tensorflow as tf


In [2]:
x = tf.constant([5, 4, 6])
y = tf.constant([5])
tf.math.less(x, y)


<tf.Tensor: shape=(3,), dtype=bool, numpy=array([False,  True, False])>

In [3]:
tf.cast(tf.math.less(y, x), dtype='float32')

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>

In [4]:
phi = tf.constant([[[0, 12],[4, 6]],[[0, 12],[4, 6]]], dtype='float32')
ron = tf.constant([10], dtype='float32')
alpha = tf.constant([0.6], dtype='float32')

In [5]:
cond_1 = tf.cast(tf.less_equal(phi, 0.5 * ron), dtype='float32')
cond_2 = tf.cast(tf.logical_and(tf.less(0.5 * ron, phi), tf.less(phi, ron)), dtype='float32')
cond_3 = tf.cast(tf.greater_equal(phi, ron), dtype='float32')

term_1 = tf.math.multiply(cond_1, 2.0 * phi / ron)
term_2 = tf.math.multiply(cond_2, 2.0 - 2.0 * phi / ron)
term_3 = tf.math.multiply(cond_3, alpha * phi)

In [6]:
cond_3 #+ cond_2 + cond_3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 1.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.]]], dtype=float32)>

In [7]:
term_1 + term_2 + term_3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0.        , 7.2000003 ],
        [0.8       , 0.79999995]],

       [[0.        , 7.2000003 ],
        [0.8       , 0.79999995]]], dtype=float32)>

In [17]:
time = tf.constant([1,2,3], dtype='float32')
s = tf.constant([0], dtype='float32')
tau = tf.constant([[8],[7],[6],[4]], dtype='float32')
tau = tf.transpose(tau)

In [18]:
def phi_fast(time, s, tau):
    x = tf.math.subtract(time, s)
    # x = tf.math.multiply(x, tau)
    x = tf.math.floormod(x, tau)
    x = tf.math.divide(x, tau)
    return x

In [19]:
phi_fast(time,s,)

InvalidArgumentError: {{function_node __wrapped__FloorMod_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [1,4] [Op:FloorMod]

In [11]:
time.shape

TensorShape([3])

In [12]:
tau.shape

TensorShape([4, 1])

In [13]:
tf.transpose(time)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [14]:
x1 = tf.math.floormod(time, tau)

In [15]:
x3 = tf.math.floormod(tf.transpose(time), tau)

In [16]:
print('x1: ', x1, 'x3: ', x3)

x1:  tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]], shape=(4, 3), dtype=float32) x3:  tf.Tensor(
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]], shape=(4, 3), dtype=float32)


In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv("smaller_train.csv")
df_valid = pd.read_csv("smaller_valid.csv")
df_test = pd.read_csv("smaller_test.csv")

df = pd.concat([df_train, df_valid, df_test], ignore_index=True)

In [6]:
df.describe()

transaction     journey_id    channel_id     timestamp  \
count  22292.00000   22292.000000  22292.000000  22292.000000   
mean       0.84712  132891.073255      3.855643   3629.303122   
std        0.35988    4211.632516      3.123650   1619.506412   
min        0.00000  120006.000000      1.000000     15.216474   
25%        1.00000  131467.000000      1.000000   2320.991985   
50%        1.00000  133157.000000      3.000000   3575.532117   
75%        1.00000  135552.750000      6.000000   5090.889078   
max        1.00000  139993.000000     24.000000   6359.766205   

       timestamp_conversion             s  
count          18884.000000  22292.000000  
mean            3969.179627      1.536874  
std             1577.755108      0.498650  
min              212.363611      1.000000  
25%             2708.432778      1.000000  
50%             3998.176944      2.000000  
75%             5439.711111      2.000000  
max             6920.170556      2.000000